import{createClient}from'https://esm.sh/@supabase/supabase-js@2';const c=createClient(CKWEB_SUPABASE.url,CKWEB_SUPABASE.publishableKey),$=s=>document.querySelector(s);let u,projects=[],pid,cid,files=[];const e=s=>String(s||'').replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]));
async function load(){let{data}=await c.from('projects').select('*').order('created_at');projects=data||[];let conv=pid?(await c.from('conversations').select('*').eq('project_id',pid).order('created_at')).data||[]:[];$('#projects').innerHTML=projects.filter(p=>!p.parent_id).map(p=>`<button class="project" data-p="${p.id}"><b>▾ ${e(p.name)}</b></button>${projects.filter(x=>x.parent_id===p.id).map(x=>`<button class="project child" data-p="${x.id}"><b>▾ ${e(x.name)}</b></button>`).join('')}`).join('')+(pid?conv.map(x=>`<button class="project convo ${x.id===cid?'active':''}" data-c="${x.id}">◌ ${e(x.title)}</button>`).join(''):'' );document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>pickProject(b.dataset.p));document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>pickConversation(b.dataset.c))}
async function pickProject(x){pid=x;cid=null;let p=projects.find(q=>q.id===x);$('#project-title').textContent=p.name;$('#project-kicker').textContent='專案';$('#delete-project').classList.remove('hidden');$('#composer').classList.add('hidden');load()}async function pickConversation(x){cid=x;$('#project-kicker').textContent='對話';$('#composer').classList.remove('hidden');let{data}=await c.from('messages').select('*,message_attachments(files(name,storage_path))').eq('conversation_id',x).order('created_at');$('#messages').innerHTML=(data||[]).map(m=>`<article class="message ${m.role}"><small>${m.role==='user'?'你':'CODEX'}</small><div class="bubble">${e(m.content)}${m.message_attachments?.map(a=>`<div>🖼 ${e(a.files.name)}</div>`).join('')||''}</div></article>`).join('')||'<div class="empty">開始這段對話。</div>';$('#messages').scrollTop=999999;load()}
function open(parent){$('#parent-id').value=parent||'';$('#project-form-title').textContent=parent?'新增子專案':'新增專案';$('#project-dialog').showModal()}$('#new-project').onclick=()=>open();$('#new-child').onclick=()=>pid&&open(pid);$('#new-chat').onclick=async()=>{if(!pid)return;let{data}=await c.from('conversations').insert({owner_id:u.id,project_id:pid,title:'新對話'}).select().single();pickConversation(data.id)};$('#delete-project').onclick=async()=>{if(pid&&confirm('永久刪除這個專案與全部子專案？')){await c.from('projects').delete().eq('id',pid);pid=cid=null;$('#delete-project').classList.add('hidden');$('#project-title').textContent='你的 AI 工作台';load()}};
$('#project-form').onsubmit=async ev=>{ev.preventDefault();let f=ev.currentTarget,d=Object.fromEntries(new FormData(f)),{data}=await c.from('projects').insert({owner_id:u.id,...d,parent_id:d.parent_id||null}).select().single();f.reset();$('#project-dialog').close();pickProject(data.id)};
function add(fs){for(let f of fs)if(['image/png','image/jpeg','image/webp'].includes(f.type)&&f.size<=10*1024*1024)files.push(f);$('#previews').textContent=files.map(f=>`🖼 ${f.name}`).join('　')}$('#images').onchange=e=>add(e.target.files);$('#composer').onpaste=e=>add([...e.clipboardData.items].filter(x=>x.type.startsWith('image/')).map(x=>x.getAsFile()));
$('#composer').onsubmit=async ev=>{ev.preventDefault();let text=$('#prompt').value.trim();if(!text&&!files.length)return;let{data:t}=await c.from('tasks').insert({owner_id:u.id,project_id:pid,title:text.slice(0,80)||'圖片分析',instructions:text||'請分析附圖。',status:'queued'}).select().single(),{data:m}=await c.from('messages').insert({owner_id:u.id,project_id:pid,conversation_id:cid,task_id:t.id,role:'user',content:text||'請分析附圖。'}).select().single();for(let f of files){let path=`${u.id}/${pid}/${crypto.randomUUID()}-${f.name}`;await c.storage.from('task-files').upload(path,f);let{data:row}=await c.from('files').insert({owner_id:u.id,project_id:pid,storage_path:path,name:f.name,mime_type:f.type,size:f.size}).select().single();await c.from('message_attachments').insert({message_id:m.id,file_id:row.id});await c.from('task_files').insert({task_id:t.id,file_id:row.id})}files=[];$('#previews').textContent='';$('#prompt').value='';pickConversation(cid)};
const say=(m,ok)=>{let n=$('#notice');n.textContent=m;n.style.color=ok?'#27855d':'#c33'},creds=()=>({email:$('#email').value.trim(),password:$('#password').value});
$('#login').onsubmit=async ev=>{ev.preventDefault();let{email,password}=creds();if(!email||!password)return say('請輸入 Email 與密碼');let{error}=await c.auth.signInWithPassword({email,password});say(error?.message||'')};
$('#signup').onclick=async()=>{let{email,password}=creds();if(!email||!password)return say('請先輸入 Email 與密碼，再建立帳號');if(password.length<6)return say('密碼至少需要 6 個字元');let{data,error}=await c.auth.signUp({email,password});if(error)return say(error.message);say(data.session?'帳號已建立，正在進入工作台…':'帳號已建立，請到信箱點擊確認信後再登入。',true)};
$('#google').onclick=async()=>{let{error}=await c.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});if(error)say(error.message)};$('#logout').onclick=()=>c.auth.signOut();const ago=ms=>ms<60000?`${Math.round(ms/1000)} 秒`:ms<3600000?`${Math.round(ms/60000)} 分鐘`:`${Math.round(ms/3600000)} 小時`;
async function pulse(){let n=$('#worker-status'),{data,error}=await c.from('workers').select('last_seen_at').order('last_seen_at',{ascending:false}).limit(1);if(error)return n.className='unknown',n.textContent='◌ 工作器狀態未知';let w=data?.[0];if(!w)return n.className='offline',n.textContent='● 未註冊工作器';let gap=Date.now()-new Date(w.last_seen_at).getTime(),live=gap<30000;n.className=live?'':'offline';n.textContent=live?'● 工作器':`● 工作器離線（${ago(gap)}前）`}
let hb;async function ses(s){u=s?.user;$('#auth').classList.toggle('hidden',!!u);$('#app').classList.toggle('hidden',!u);if(u){load();pulse();hb=hb||setInterval(pulse,10000)}else{clearInterval(hb);hb=null}}let{data:{session:s}}=await c.auth.getSession();ses(s);c.auth.onAuthStateChange((_e,s)=>ses(s));
